/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 6c4a0d6f7abbb40b4324df3d73f587ee)
interface __BaseEnv_Env {
	SCRAPE_RESPONSES_BUCKET: R2Bucket;
	SCRAPE_QUEUE: Queue;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
